<a href="https://colab.research.google.com/github/abdull254/Class_Project/blob/main/wikiart.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
!pip install -q huggingface_hub

In [16]:
from huggingface_hub import hf_hub_download

file1 = hf_hub_download(
    repo_id="huggan/wikiart",
    filename="data/train-00000-of-00072.parquet",
    repo_type="dataset"
)

file2 = hf_hub_download(
    repo_id="huggan/wikiart",
    filename="data/train-00001-of-00072.parquet",
    repo_type="dataset"
)
file3 = hf_hub_download(
    repo_id="huggan/wikiart",
    filename="data/train-00002-of-00072.parquet",
    repo_type="dataset"
)

file4 = hf_hub_download(
    repo_id="huggan/wikiart",
    filename="data/train-00004-of-00072.parquet",
    repo_type="dataset"
)
print(file3)
print(file4)

data/train-00002-of-00072.parquet: reconstructing file:   0%|          |  0.00B /  533MB

data/train-00002-of-00072.parquet: downloading bytes:           |  0.00B

data/train-00004-of-00072.parquet: reconstructing file:   0%|          |  0.00B /  532MB

data/train-00004-of-00072.parquet: downloading bytes:           |  0.00B

/root/.cache/huggingface/hub/datasets--huggan--wikiart/snapshots/d559852d2b232e0fcf195e775866964f0564f2b5/data/train-00002-of-00072.parquet
/root/.cache/huggingface/hub/datasets--huggan--wikiart/snapshots/d559852d2b232e0fcf195e775866964f0564f2b5/data/train-00004-of-00072.parquet

In [17]:
for f in [file1, file2,file3,file4 ]:
    with open(f, "rb") as file:
        start = file.read(4)

    with open(f, "rb") as file:
        file.seek(-4, 2)
        end = file.read(4)

    print(f)
    print("START:", start)
    print("END:", end)

/root/.cache/huggingface/hub/datasets--huggan--wikiart/snapshots/d559852d2b232e0fcf195e775866964f0564f2b5/data/train-00000-of-00072.parquet
START: b'PAR1'
END: b'PAR1'
/root/.cache/huggingface/hub/datasets--huggan--wikiart/snapshots/d559852d2b232e0fcf195e775866964f0564f2b5/data/train-00001-of-00072.parquet
START: b'PAR1'
END: b'PAR1'
/root/.cache/huggingface/hub/datasets--huggan--wikiart/snapshots/d559852d2b232e0fcf195e775866964f0564f2b5/data/train-00002-of-00072.parquet
START: b'PAR1'
END: b'PAR1'
/root/.cache/huggingface/hub/datasets--huggan--wikiart/snapshots/d559852d2b232e0fcf195e775866964f0564f2b5/data/train-00004-of-00072.parquet
START: b'PAR1'
END: b'PAR1'

In [21]:
import pandas as pd

df1 = pd.read_parquet(file1)
df2 = pd.read_parquet(file2)
df3 = pd.read_parquet(file3)
df4 = pd.read_parquet(file4)

df = pd.concat([df1, df2, df3,df4], ignore_index=True)

print("Shape:", df.shape)
print("\nColumns:")
print(df.columns)

display(df.head())

Shape: (4528, 4)

Columns:
Index(['image', 'artist', 'genre', 'style'], dtype='object')

                                               image  artist  genre  style
0  {'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...      22      4     21
1  {'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...      20      7      4
2  {'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...      16      6     20
3  {'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...      17      2     12
4  {'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...       9     10     23

In [22]:
from datasets import load_dataset_builder

builder = load_dataset_builder("huggan/wikiart")
features = builder.info.features

print(features)

Resolving data files:   0%|          | 0/72 [00:00<?, ?it/s]

{'image': Image(mode=None, decode=True), 'artist': ClassLabel(names=['Unknown Artist', 'boris-kustodiev', 'camille-pissarro', 'childe-hassam', 'claude-monet', 'edgar-degas', 'eugene-boudin', 'gustave-dore', 'ilya-repin', 'ivan-aivazovsky', 'ivan-shishkin', 'john-singer-sargent', 'marc-chagall', 'martiros-saryan', 'nicholas-roerich', 'pablo-picasso', 'paul-cezanne', 'pierre-auguste-renoir', 'pyotr-konchalovsky', 'raphael-kirchner', 'rembrandt', 'salvador-dali', 'vincent-van-gogh', 'hieronymus-bosch', 'leonardo-da-vinci', 'albrecht-durer', 'edouard-cortes', 'sam-francis', 'juan-gris', 'lucas-cranach-the-elder', 'paul-gauguin', 'konstantin-makovsky', 'egon-schiele', 'thomas-eakins', 'gustave-moreau', 'francisco-goya', 'edvard-munch', 'henri-matisse', 'fra-angelico', 'maxime-maufra', 'jan-matejko', 'mstislav-dobuzhinsky', 'alfred-sisley', 'mary-cassatt', 'gustave-loiseau', 'fernando-botero', 'zinaida-serebriakova', 'georges-seurat', 'isaac-levitan', 'joaquã\xadn-sorolla', 'jacek-malczewski', 'berthe-morisot', 'andy-warhol', 'arkhip-kuindzhi', 'niko-pirosmani', 'james-tissot', 'vasily-polenov', 'valentin-serov', 'pietro-perugino', 'pierre-bonnard', 'ferdinand-hodler', 'bartolome-esteban-murillo', 'giovanni-boldini', 'henri-martin', 'gustav-klimt', 'vasily-perov', 'odilon-redon', 'tintoretto', 'gene-davis', 'raphael', 'john-henry-twachtman', 'henri-de-toulouse-lautrec', 'antoine-blanchard', 'david-burliuk', 'camille-corot', 'konstantin-korovin', 'ivan-bilibin', 'titian', 'maurice-prendergast', 'edouard-manet', 'peter-paul-rubens', 'aubrey-beardsley', 'paolo-veronese', 'joshua-reynolds', 'kuzma-petrov-vodkin', 'gustave-caillebotte', 'lucian-freud', 'michelangelo', 'dante-gabriel-rossetti', 'felix-vallotton', 'nikolay-bogdanov-belsky', 'georges-braque', 'vasily-surikov', 'fernand-leger', 'konstantin-somov', 'katsushika-hokusai', 'sir-lawrence-alma-tadema', 'vasily-vereshchagin', 'ernst-ludwig-kirchner', 'mikhail-vrubel', 'orest-kiprensky', 'william-merritt-chase', 'aleksey-savrasov', 'hans-memling', 'amedeo-modigliani', 'ivan-kramskoy', 'utagawa-kuniyoshi', 'gustave-courbet', 'william-turner', 'theo-van-rysselberghe', 'joseph-wright', 'edward-burne-jones', 'koloman-moser', 'viktor-vasnetsov', 'anthony-van-dyck', 'raoul-dufy', 'frans-hals', 'hans-holbein-the-younger', 'ilya-mashkov', 'henri-fantin-latour', 'm.c.-escher', 'el-greco', 'mikalojus-ciurlionis', 'james-mcneill-whistler', 'karl-bryullov', 'jacob-jordaens', 'thomas-gainsborough', 'eugene-delacroix', 'canaletto']), 'genre': ClassLabel(names=['abstract_painting', 'cityscape', 'genre_painting', 'illustration', 'landscape', 'nude_painting', 'portrait', 'religious_painting', 'sketch_and_study', 'still_life', 'Unknown Genre']), 'style': ClassLabel(names=['Abstract_Expressionism', 'Action_painting', 'Analytical_Cubism', 'Art_Nouveau', 'Baroque', 'Color_Field_Painting', 'Contemporary_Realism', 'Cubism', 'Early_Renaissance', 'Expressionism', 'Fauvism', 'High_Renaissance', 'Impressionism', 'Mannerism_Late_Renaissance', 'Minimalism', 'Naive_Art_Primitivism', 'New_Realism', 'Northern_Renaissance', 'Pointillism', 'Pop_Art', 'Post_Impressionism', 'Realism', 'Rococo', 'Romanticism', 'Symbolism', 'Synthetic_Cubism', 'Ukiyo_e'])}

In [23]:
df["artist_name"] = df["artist"].apply(
    lambda x: features["artist"].int2str(x)
)

df["genre_name"] = df["genre"].apply(
    lambda x: features["genre"].int2str(x)
)

df["style_name"] = df["style"].apply(
    lambda x: features["style"].int2str(x)
)

display(
    df[["artist_name", "genre_name", "style_name"]].head(10)
)

             artist_name          genre_name            style_name
0       vincent-van-gogh           landscape               Realism
1              rembrandt  religious_painting               Baroque
2           paul-cezanne            portrait    Post_Impressionism
3  pierre-auguste-renoir      genre_painting         Impressionism
4        ivan-aivazovsky       Unknown Genre           Romanticism
5        boris-kustodiev      genre_painting           Art_Nouveau
6       vincent-van-gogh       Unknown Genre               Realism
7        ivan-aivazovsky           landscape           Romanticism
8         albrecht-durer  religious_painting  Northern_Renaissance
9    john-singer-sargent            portrait               Realism

In [24]:
print(df["style_name"].value_counts())

style_name
Impressionism             1347
Realism                    851
Post_Impressionism         456
Symbolism                  337
Romanticism                332
Art_Nouveau                311
Northern_Renaissance       205
Baroque                    188
Expressionism              188
Naive_Art_Primitivism      159
Cubism                     103
Pointillism                 14
Synthetic_Cubism            12
Analytical_Cubism           11
Fauvism                      7
Abstract_Expressionism       7
Name: count, dtype: int64

In [25]:
print("Unique artists:", df["artist_name"].nunique())

print(df["artist_name"].value_counts().head(20))

Unique artists: 24
artist_name
vincent-van-gogh         443
nicholas-roerich         437
pierre-auguste-renoir    342
claude-monet             315
pyotr-konchalovsky       226
camille-pissarro         203
rembrandt                188
albrecht-durer           178
pablo-picasso            174
john-singer-sargent      174
boris-kustodiev          174
gustave-dore             172
marc-chagall             162
edgar-degas              152
martiros-saryan          149
paul-cezanne             138
ivan-aivazovsky          137
childe-hassam            135
eugene-boudin            131
ilya-repin               131
Name: count, dtype: int64

In [26]:
SHARED_STYLES = [
    "Realism",
    "Baroque",
    "Romanticism",
    "Rococo"
]

wikiart_shared = df[
    df["style_name"].isin(SHARED_STYLES)
]

print(wikiart_shared["style_name"].value_counts())

style_name
Realism        851
Romanticism    332
Baroque        188
Name: count, dtype: int64

In [27]:
print(df["style_name"].value_counts())

style_name
Impressionism             1347
Realism                    851
Post_Impressionism         456
Symbolism                  337
Romanticism                332
Art_Nouveau                311
Northern_Renaissance       205
Baroque                    188
Expressionism              188
Naive_Art_Primitivism      159
Cubism                     103
Pointillism                 14
Synthetic_Cubism            12
Analytical_Cubism           11
Fauvism                      7
Abstract_Expressionism       7
Name: count, dtype: int64

In [28]:
import pandas as pd
import pyarrow.parquet as pq
from huggingface_hub import HfFileSystem

fs = HfFileSystem()
files = sorted(fs.glob("datasets/huggan/wikiart/data/*.parquet"))
print(len(files), "files")

parts = []
for i, f in enumerate(files, 1):
    with fs.open(f, "rb") as fh:
        parts.append(pq.read_table(fh, columns=["artist", "genre", "style"]).to_pandas())
    print(i, "/", len(files))

labels = pd.concat(parts, ignore_index=True)

# numbers -> names (uses the 'features' you already loaded)
for c in ["artist", "genre", "style"]:
    labels[c] = labels[c].apply(features[c].int2str)

labels.to_csv("wikiart_labels.csv", index=False)
print("Total images:", len(labels))
print("Artists:", labels["artist"].nunique())
print(labels["style"].value_counts())

72 files
1 / 72
2 / 72
3 / 72
4 / 72
5 / 72
6 / 72
7 / 72
8 / 72
9 / 72
10 / 72
11 / 72
12 / 72
13 / 72
14 / 72
15 / 72
16 / 72
17 / 72
18 / 72
19 / 72
20 / 72
21 / 72
22 / 72
23 / 72
24 / 72
25 / 72
26 / 72
27 / 72
28 / 72
29 / 72
30 / 72
31 / 72
32 / 72
33 / 72
34 / 72
35 / 72
36 / 72
37 / 72
38 / 72
39 / 72
40 / 72
41 / 72
42 / 72
43 / 72
44 / 72
45 / 72
46 / 72
47 / 72
48 / 72
49 / 72
50 / 72
51 / 72
52 / 72
53 / 72
54 / 72
55 / 72
56 / 72
57 / 72
58 / 72
59 / 72
60 / 72
61 / 72
62 / 72
63 / 72
64 / 72
65 / 72
66 / 72
67 / 72
68 / 72
69 / 72
70 / 72
71 / 72
72 / 72
Total images: 81444
Artists: 129
style
Impressionism                 13060
Realism                       10733
Romanticism                    7019
Expressionism                  6736
Post_Impressionism             6450
Symbolism                      4528
Art_Nouveau                    4334
Baroque                        4240
Abstract_Expressionism         2782
Northern_Renaissance           2552
Naive_Art_Primitivism          2405
Cubism                         2235
Rococo                         2089
Color_Field_Painting           1615
Pop_Art                        1483
Early_Renaissance              1391
High_Renaissance               1343
Minimalism                     1337
Mannerism_Late_Renaissance     1279
Ukiyo_e                        1167
Fauvism                         934
Pointillism                     513
Contemporary_Realism            481
New_Realism                     314
Synthetic_Cubism                216
Analytical_Cubism               110
Action_painting                  98
Name: count, dtype: int64

In [30]:
pip install imagehash

Collecting imagehash
  Downloading ImageHash-4.3.2-py2.py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: PyWavelets in /usr/local/lib/python3.13/dist-packages (from imagehash) (1.10.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from imagehash) (2.1.3)
Requirement already satisfied: pillow in /usr/local/lib/python3.13/dist-packages (from imagehash) (11.3.0)
Requirement already satisfied: scipy in /usr/local/lib/python3.13/dist-packages (from imagehash) (1.16.3)
Downloading ImageHash-4.3.2-py2.py3-none-any.whl (296 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.7/296.7 kB 6.3 MB/s eta 0:00:00
Installing collected packages: imagehash
Successfully installed imagehash-4.3.2

In [31]:
"""
color_baseline_10styles.py
Color-only baseline on the new 10-style WikiArt (huggan/wikiart).

Same idea as the first baseline (logistic regression on 32 color features,
class-weighted, 70/15/15, seed 42), but:
  - 10 styles instead of 13 (chance = 10%)
  - runs TWICE: random split vs artist-disjoint split
  - also reports top-3 accuracy and majority floor
  - cleans the sample first: broken files, duplicates, conflicting labels,
    and flags black-and-white images (cleaning_report.csv)

Run in Colab:
  !pip install -q huggingface_hub pyarrow scikit-learn pillow pandas matplotlib datasets imagehash
  %run color_baseline_10styles.py
It reads only the sampled images, one parquet file at a time.
"""
import io, json, os, random
import numpy as np
import pyarrow.parquet as pq
from PIL import Image
import imagehash
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import train_test_split, StratifiedGroupKFold
from sklearn.metrics import accuracy_score, f1_score, top_k_accuracy_score, classification_report

REPO = "huggan/wikiart"
PER_STYLE = 300          # images per style (3,000 total), same size as before
SEED = 42
OUT = "baseline_10styles"
STYLES = ["Early_Renaissance", "High_Renaissance", "Northern_Renaissance",
          "Mannerism_Late_Renaissance", "Baroque", "Rococo", "Romanticism",
          "Realism", "Impressionism", "Post_Impressionism"]


# ---------------------------------------------------------------- data access
def list_files():
    from huggingface_hub import HfFileSystem
    fs = HfFileSystem()
    return fs, sorted(fs.glob(f"datasets/{REPO}/data/*.parquet"))


def style_names():
    from datasets import load_dataset_builder
    feats = load_dataset_builder(REPO).info.features
    return feats["style"].names, feats["artist"].names


# ---------------------------------------------------------------- features
def image_checks(img_bytes):
    """Perceptual hash (finds near-identical images) and a black-and-white flag."""
    img = Image.open(io.BytesIO(img_bytes)).convert("RGB")
    img.thumbnail((256, 256))
    sat = np.asarray(img.convert("HSV"), dtype=np.float32)[..., 1] / 255.0
    return str(imagehash.phash(img)), bool(sat.mean() < 0.05)


def color_features(img_bytes):
    """32 color features: RGB+HSV mean/std (12), hue hist (12), sat hist (4), value hist (4)."""
    img = Image.open(io.BytesIO(img_bytes)).convert("RGB")
    img.thumbnail((128, 128))
    rgb = np.asarray(img, dtype=np.float32) / 255.0
    hsv = np.asarray(img.convert("HSV"), dtype=np.float32) / 255.0
    px_rgb, px_hsv = rgb.reshape(-1, 3), hsv.reshape(-1, 3)
    stats = np.concatenate([px_rgb.mean(0), px_rgb.std(0), px_hsv.mean(0), px_hsv.std(0)])
    h = np.histogram(px_hsv[:, 0], bins=12, range=(0, 1))[0]
    s = np.histogram(px_hsv[:, 1], bins=4, range=(0, 1))[0]
    v = np.histogram(px_hsv[:, 2], bins=4, range=(0, 1))[0]
    n = len(px_hsv)
    return np.concatenate([stats, h / n, s / n, v / n])


# ---------------------------------------------------------------- sampling
def sample_rows(fs, files, style_list):
    """Reads only the style/artist columns to pick PER_STYLE random rows per style."""
    parts, offset = [], 0
    for f in files:
        with fs.open(f, "rb") as fh:
            t = pq.read_table(fh, columns=["artist", "style"]).to_pandas()
        t["file"], t["local"] = f, np.arange(len(t))
        parts.append(t)
    lab = pd.concat(parts, ignore_index=True)
    lab["style_name"] = lab["style"].map(lambda i: style_list[i])
    lab = lab[lab["style_name"].isin(STYLES)]
    return pd.concat([g.sample(min(PER_STYLE, len(g)), random_state=SEED)
                      for _, g in lab.groupby("style_name")])


def extract(fs, sample):
    """Opens each file once and reads only the row groups that hold sampled rows."""
    feats, keep, hashes, gray, broken = [], [], [], [], 0
    for k, (f, g) in enumerate(sample.groupby("file"), 1):
        with fs.open(f, "rb") as fh:
            pf = pq.ParquetFile(fh)
            starts = np.cumsum([0] + [pf.metadata.row_group(i).num_rows
                                      for i in range(pf.num_row_groups)])
            wanted = set(g["local"])
            for rg in range(pf.num_row_groups):
                rows = [r for r in wanted if starts[rg] <= r < starts[rg + 1]]
                if not rows:
                    continue
                col = pf.read_row_group(rg, columns=["image"]).column("image").to_pylist()
                for r in rows:
                    try:
                        b = col[r - starts[rg]]["bytes"]
                        f_ = color_features(b)
                        h_, bw_ = image_checks(b)
                    except Exception as e:
                        broken += 1
                        if broken <= 3:
                            print(f"  image failed: {type(e).__name__}: {e}")
                        continue
                    feats.append(f_); hashes.append(h_); gray.append(bw_)
                    keep.append(g.index[g["local"] == r][0])
        print(f"  file {k}/{sample['file'].nunique()} done, {len(feats)} images so far")
        if k == 1 and not feats:
            raise RuntimeError("Every image in the first file failed. See the error above and fix it first.")
    out = sample.loc[keep].copy()
    out["phash"], out["grayscale"] = hashes, gray
    return np.vstack(feats), out, broken


def clean(X, sample, broken):
    """Removes duplicates. Same style: keep one copy. Different styles: drop all copies."""
    n0 = len(sample)
    sample = sample.reset_index(drop=True)
    drop = set()
    dup_same = dup_conflict = 0
    for h, g in sample.groupby("phash"):
        if len(g) < 2:
            continue
        if g["style_name"].nunique() == 1:
            drop.update(g.index[1:]); dup_same += len(g) - 1
        else:
            drop.update(g.index); dup_conflict += len(g)
    keep = np.array([i for i in range(len(sample)) if i not in drop], dtype=int)
    report = pd.DataFrame([
        ("sampled", n0 + broken),
        ("broken files removed", broken),
        ("duplicate copies removed (same style)", dup_same),
        ("images removed (duplicates with different styles)", dup_conflict),
        ("black-and-white images (kept, flagged)", int(sample["grayscale"].sum())),
        ("final images", len(keep)),
    ], columns=["step", "images"])
    return X[keep], sample.loc[keep], report


# ---------------------------------------------------------------- evaluation
def evaluate(name, Xtr, ytr, Xte, yte, classes):
    model = make_pipeline(StandardScaler(),
                          LogisticRegression(max_iter=3000, class_weight="balanced"))
    model.fit(Xtr, ytr)
    pred, proba = model.predict(Xte), model.predict_proba(Xte)
    majority = pd.Series(ytr).value_counts().idxmax()
    res = {
        "split": name,
        "n_train": int(len(ytr)), "n_test": int(len(yte)),
        "accuracy": round(accuracy_score(yte, pred), 3),
        "top3_accuracy": round(top_k_accuracy_score(yte, proba, k=3, labels=model.classes_), 3),
        "macro_f1": round(f1_score(yte, pred, average="macro"), 3),
        "chance": round(1 / len(classes), 3),
        "majority_floor": round(float(np.mean(np.array(yte) == majority)), 3),
    }
    rep = classification_report(yte, pred, output_dict=True, zero_division=0)
    per_style = {c: round(rep[c]["f1-score"], 3) for c in classes if c in rep}
    return res, per_style


def split_random(y):
    idx = np.arange(len(y))
    tr, tmp = train_test_split(idx, test_size=0.30, stratify=y, random_state=SEED)
    va, te = train_test_split(tmp, test_size=0.50, stratify=y[tmp], random_state=SEED)
    return tr, va, te


def split_artist(y, groups):
    """About 70/15/15, and every artist is in only one part."""
    folds = list(StratifiedGroupKFold(n_splits=7, shuffle=True, random_state=SEED).split(y, y, groups))
    te, va = folds[0][1], folds[1][1]
    tr = np.setdiff1d(np.arange(len(y)), np.concatenate([te, va]))
    return tr, va, te


def main():
    random.seed(SEED); np.random.seed(SEED)
    os.makedirs(OUT, exist_ok=True)
    style_list, artist_list = style_names()
    fs, files = list_files()
    print(f"{len(files)} parquet files")

    print("Picking the sample (labels only) ...")
    sample = sample_rows(fs, files, style_list)
    print(sample["style_name"].value_counts().to_string())

    print("Extracting color features ...")
    X, sample, broken = extract(fs, sample)

    print("Cleaning ...")
    X, sample, report = clean(X, sample, broken)
    report.to_csv(f"{OUT}/cleaning_report.csv", index=False)
    print(report.to_string(index=False))
    print("Black-and-white images per style:")
    print(sample.groupby("style_name")["grayscale"].sum().to_string())

    y = sample["style_name"].to_numpy()
    artist = sample["artist"].map(lambda i: artist_list[i]).to_numpy()
    # each 'Unknown Artist' image is its own group, so it can't link train and test
    groups = np.where(artist == "Unknown Artist",
                      ["unknown_" + str(i) for i in sample.index], artist)
    np.savez(f"{OUT}/features.npz", X=X, y=y, artist=artist, grayscale=sample["grayscale"].to_numpy())
    unknown_share = float(np.mean(artist == "Unknown Artist"))

    results, per_style = [], {}
    for name, (tr, va, te) in [("random", split_random(y)),
                               ("artist-disjoint", split_artist(y, groups))]:
        r, ps = evaluate(name, X[tr], y[tr], X[te], y[te], STYLES)
        rv, _ = evaluate(name, X[tr], y[tr], X[va], y[va], STYLES)
        r["val_accuracy"] = rv["accuracy"]
        results.append(r); per_style[name] = ps
        print(f"\n{name}: acc {r['accuracy']}  top-3 {r['top3_accuracy']}  "
              f"macro F1 {r['macro_f1']}  (chance {r['chance']}, majority {r['majority_floor']}, "
              f"val acc {r['val_accuracy']})")

    pd.DataFrame(results).to_csv(f"{OUT}/results.csv", index=False)
    pd.DataFrame(per_style).rename_axis("style").to_csv(f"{OUT}/per_style_f1.csv")
    with open(f"{OUT}/summary.json", "w") as fh:
        json.dump({"per_style": PER_STYLE, "seed": SEED, "unknown_artist_share": round(unknown_share, 3),
                   "results": results}, fh, indent=2)

    try:
        import matplotlib; matplotlib.use("Agg"); import matplotlib.pyplot as plt
        ps = pd.DataFrame(per_style).sort_values("random")
        ps.plot.barh(figsize=(8, 5), color=["#7A1F3D", "#C9A227"])
        plt.xlabel("F1 score (test set)"); plt.title("Color-only baseline, 10 styles")
        plt.tight_layout(); plt.savefig(f"{OUT}/per_style_f1.png", dpi=150); plt.close()
    except Exception as e:
        print("chart skipped:", e)

    print(f"\nUnknown Artist share in this sample: {unknown_share:.1%}")
    print(pd.DataFrame(results).to_string(index=False))
    print(f"\nFiles saved in ./{OUT}/")


if __name__ == "__main__":
    main()

Resolving data files:   0%|          | 0/72 [00:00<?, ?it/s]

72 parquet files
Picking the sample (labels only) ...
style_name
Baroque                       300
Early_Renaissance             300
High_Renaissance              300
Impressionism                 300
Mannerism_Late_Renaissance    300
Northern_Renaissance          300
Post_Impressionism            300
Realism                       300
Rococo                        300
Romanticism                   300
Extracting color features ...
  file 1/72 done, 32 images so far
  file 2/72 done, 63 images so far
  file 3/72 done, 98 images so far
  file 4/72 done, 135 images so far
  file 5/72 done, 176 images so far
  file 6/72 done, 210 images so far
  file 7/72 done, 242 images so far
  file 8/72 done, 269 images so far
  file 9/72 done, 299 images so far
  file 10/72 done, 333 images so far
  file 11/72 done, 366 images so far
  file 12/72 done, 392 images so far
  file 13/72 done, 426 images so far
  file 14/72 done, 449 images so far
  file 15/72 done, 459 images so far
  file 16/72 done, 521 images so far
  file 17/72 done, 552 images so far
  file 18/72 done, 591 images so far
  file 19/72 done, 652 images so far
  file 20/72 done, 701 images so far
  file 21/72 done, 749 images so far
  file 22/72 done, 780 images so far
  file 23/72 done, 828 images so far
  file 24/72 done, 877 images so far
  file 25/72 done, 930 images so far
  file 26/72 done, 974 images so far
  file 27/72 done, 1022 images so far
  file 28/72 done, 1077 images so far
  file 29/72 done, 1131 images so far
  file 30/72 done, 1184 images so far
  file 31/72 done, 1240 images so far
  file 32/72 done, 1288 images so far
  file 33/72 done, 1341 images so far
  file 34/72 done, 1394 images so far
  file 35/72 done, 1444 images so far
  file 36/72 done, 1493 images so far
  file 37/72 done, 1534 images so far
  file 38/72 done, 1596 images so far
  file 39/72 done, 1649 images so far
  file 40/72 done, 1711 images so far
  file 41/72 done, 1759 images so far
  file 42/72 done, 1806 images so far
  file 43/72 done, 1845 images so far
  file 44/72 done, 1887 images so far
  file 45/72 done, 1928 images so far
  file 46/72 done, 1970 images so far
  file 47/72 done, 2009 images so far
  file 48/72 done, 2033 images so far
  file 49/72 done, 2070 images so far
  file 50/72 done, 2210 images so far
  file 51/72 done, 2295 images so far
  file 52/72 done, 2332 images so far
  file 53/72 done, 2357 images so far
  file 54/72 done, 2392 images so far
  file 55/72 done, 2420 images so far
  file 56/72 done, 2459 images so far
  file 57/72 done, 2509 images so far
  file 58/72 done, 2559 images so far
  file 59/72 done, 2592 images so far
  file 60/72 done, 2595 images so far
  file 61/72 done, 2626 images so far
  file 62/72 done, 2664 images so far
  file 63/72 done, 2702 images so far
  file 64/72 done, 2736 images so far
  file 65/72 done, 2769 images so far
  file 66/72 done, 2795 images so far
  file 67/72 done, 2830 images so far
  file 68/72 done, 2871 images so far
  file 69/72 done, 2889 images so far
  file 70/72 done, 2929 images so far
  file 71/72 done, 2979 images so far
  file 72/72 done, 3000 images so far
Cleaning ...
                                             step  images
                                          sampled    3000
                             broken files removed       0
            duplicate copies removed (same style)       0
images removed (duplicates with different styles)       0
           black-and-white images (kept, flagged)     209
                                     final images    3000
Black-and-white images per style:
style_name
Baroque                        6
Early_Renaissance              9
High_Renaissance              19
Impressionism                  0
Mannerism_Late_Renaissance     6
Northern_Renaissance          91
Post_Impressionism             7
Realism                       19
Rococo                        11
Romanticism                   41

random: acc 0.258  top-3 0.562  macro F1 0.248  (chance 0.1, majority 0.1, val acc 0.256)

artist-disjoint: acc 0.209  top-3 0.515  macro F1 0.181  (chance 0.1, majority 0.029, val acc 0.209)

Unknown Artist share in this sample: 53.0%
          split  n_train  n_test  accuracy  top3_accuracy  macro_f1  chance  majority_floor  val_accuracy
         random     2100     450     0.258          0.562     0.248     0.1           0.100         0.256
artist-disjoint     2038     618     0.209          0.515     0.181     0.1           0.029         0.209

Files saved in ./baseline_10styles/